-- DROP TABLE IF EXISTS CASE;
-- CREATE TABLE CASE
-- (
--   ID          INTEGER PRIMARY KEY AUTO_INCREMENT,
--   CASE_NUMBER VARCHAR(100) NOT NULL,
-- );
--
-- DROP TABLE IF EXISTS SERVICE_IN_CASE;
-- CREATE TABLE SERVICE_IN_CASE
-- (
--   ID      INTEGER PRIMARY KEY AUTO_INCREMENT,
--   CASE_ID INTEGER NOT NULL,
--
--   CONSTRAINT FK_SERVICE_IN_CASE FOREIGN KEY (CASE_ID) references CASE (ID)
-- );

//todo create schema for h2